//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string id { get; set; }
        public string Resturantid { get; set; }
        public string name { get; set; }
        public string quantity { get; set; }
        public string preserve { get; set; }
        public string status { get; set; }
        public string assign { get; set; }
    }
}
